// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        Swap(super::SwapInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapInstruction {
    #[prost(uint64, tag="1")]
    pub amount_in: u64,
    #[prost(bool, tag="2")]
    pub is_swap_x_to_y: bool,
    #[prost(bytes="vec", tag="3")]
    pub c_min: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="4")]
    pub label: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4, 5, 6")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        Swap(super::SwapEvent),
        #[prost(message, tag="4")]
        InitializePool(super::InitializePoolEvent),
        #[prost(message, tag="5")]
        AddLiquidity(super::AddLiquidityEvent),
        #[prost(message, tag="6")]
        RemoveLiquidity(super::RemoveLiquidityEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapEvent {
    #[prost(bytes="vec", tag="1")]
    pub trader: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub direction: u32,
    #[prost(uint64, tag="3")]
    pub deadline: u64,
    #[prost(uint64, tag="4")]
    pub trade_fee: u64,
    #[prost(uint64, tag="5")]
    pub protocol_fee: u64,
    #[prost(uint64, tag="6")]
    pub amount_in: u64,
    #[prost(uint64, tag="7")]
    pub amount_out: u64,
    #[prost(uint64, tag="8")]
    pub actual_amount_in: u64,
    #[prost(uint64, tag="9")]
    pub wsol_deposit: u64,
    #[prost(uint64, tag="10")]
    pub actual_amount_out: u64,
    #[prost(uint64, tag="11")]
    pub new_reserve_x: u64,
    #[prost(uint64, tag="12")]
    pub new_reserve_y: u64,
    #[prost(uint64, tag="13")]
    pub available_reserve_x: u64,
    #[prost(uint64, tag="14")]
    pub available_reserve_y: u64,
    #[prost(uint64, tag="15")]
    pub locked_x: u64,
    #[prost(uint64, tag="16")]
    pub locked_y: u64,
    #[prost(uint64, tag="17")]
    pub user_locked_x: u64,
    #[prost(uint64, tag="18")]
    pub user_locked_y: u64,
    #[prost(uint64, tag="19")]
    pub protocol_fee_x: u64,
    #[prost(uint64, tag="20")]
    pub protocol_fee_y: u64,
    #[prost(bytes="vec", tag="21")]
    pub user_token_account_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub user_token_account_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="23")]
    pub token_mint_lp: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="24")]
    pub token_mint_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="25")]
    pub token_mint_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="26")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializePoolEvent {
    #[prost(bytes="vec", tag="1")]
    pub trader: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub liquidity_minted: u64,
    #[prost(uint64, tag="3")]
    pub sol_create_pool_fee: u64,
    #[prost(uint64, tag="4")]
    pub new_reserve_x: u64,
    #[prost(uint64, tag="5")]
    pub new_reserve_y: u64,
    #[prost(bytes="vec", tag="6")]
    pub token_mint_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_mint_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub token_mint_lp: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="9")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidityEvent {
    #[prost(bytes="vec", tag="1")]
    pub supplier: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub max_amount_x: u64,
    #[prost(uint64, tag="3")]
    pub max_amount_y: u64,
    #[prost(uint64, tag="4")]
    pub transfer_in_x: u64,
    #[prost(uint64, tag="5")]
    pub transfer_in_y: u64,
    #[prost(uint64, tag="6")]
    pub liquidity_minted: u64,
    #[prost(uint64, tag="7")]
    pub user_token_lp_balance: u64,
    #[prost(uint64, tag="8")]
    pub new_reserve_x: u64,
    #[prost(uint64, tag="9")]
    pub new_reserve_y: u64,
    #[prost(uint64, tag="10")]
    pub available_reserve_x: u64,
    #[prost(uint64, tag="11")]
    pub available_reserve_y: u64,
    #[prost(bytes="vec", tag="12")]
    pub token_mint_lp: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub token_mint_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub token_mint_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="15")]
    pub ref_code: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityEvent {
    #[prost(bytes="vec", tag="1")]
    pub supplier: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub min_amount_x: u64,
    #[prost(uint64, tag="3")]
    pub min_amount_y: u64,
    #[prost(uint64, tag="4")]
    pub transfer_out_x: u64,
    #[prost(uint64, tag="5")]
    pub transfer_out_y: u64,
    #[prost(uint64, tag="6")]
    pub liquidity_burned: u64,
    #[prost(uint64, tag="7")]
    pub user_token_lp_balance: u64,
    #[prost(uint64, tag="8")]
    pub new_reserve_x: u64,
    #[prost(uint64, tag="9")]
    pub new_reserve_y: u64,
    #[prost(uint64, tag="10")]
    pub available_reserve_x: u64,
    #[prost(uint64, tag="11")]
    pub available_reserve_y: u64,
    #[prost(bytes="vec", tag="12")]
    pub token_mint_lp: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub token_mint_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub token_mint_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="15")]
    pub label: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
