// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6, 7, 8, 9, 10, 11, 12")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        SolDepositBuy(super::SolDepositBuyInstruction),
        #[prost(message, tag="4")]
        SolWithdrawBuy(super::SolWithdrawBuyInstruction),
        #[prost(message, tag="5")]
        SolFulfillBuy(super::SolFulfillBuyInstruction),
        #[prost(message, tag="6")]
        SolFulfillSell(super::SolFulfillSellInstruction),
        #[prost(message, tag="7")]
        DepositSell(super::DepositSellInstruction),
        #[prost(message, tag="8")]
        WithdrawSell(super::WithdrawSellInstruction),
        #[prost(message, tag="9")]
        SolMip1FulfillBuy(super::SolMip1FulfillBuyInstruction),
        #[prost(message, tag="10")]
        SolMip1FulfillSell(super::SolMip1FulfillSellInstruction),
        #[prost(message, tag="11")]
        SolOcpFulfillBuy(super::SolOcpFulfillBuyInstruction),
        #[prost(message, tag="12")]
        SolOcpFulfillSell(super::SolOcpFulfillSellInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolDepositBuyInstruction {
    #[prost(uint64, tag="1")]
    pub payment_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolWithdrawBuyInstruction {
    #[prost(uint64, tag="1")]
    pub payment_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolFulfillBuyInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub min_payment_amount: u64,
    #[prost(int32, tag="3")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="4")]
    pub taker_fee_bp: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolFulfillSellInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub max_payment_amount: u64,
    #[prost(uint32, tag="3")]
    pub buyside_creator_royalty_bp: u32,
    #[prost(int32, tag="4")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="5")]
    pub taker_fee_bp: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositSellInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawSellInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolMip1FulfillBuyInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub min_payment_amount: u64,
    #[prost(int32, tag="3")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="4")]
    pub taker_fee_bp: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolMip1FulfillSellInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub max_payment_amount: u64,
    #[prost(int32, tag="3")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="4")]
    pub taker_fee_bp: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolOcpFulfillBuyInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub min_payment_amount: u64,
    #[prost(int32, tag="3")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="4")]
    pub taker_fee_bp: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolOcpFulfillSellInstruction {
    #[prost(uint64, tag="1")]
    pub asset_amount: u64,
    #[prost(uint64, tag="2")]
    pub max_payment_amount: u64,
    #[prost(int32, tag="3")]
    pub maker_fee_bp: i32,
    #[prost(int32, tag="4")]
    pub taker_fee_bp: i32,
}
// @@protoc_insertion_point(module)
