// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6, 7, 8, 9, 10, 11, 12")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        Sell(super::SellInstruction),
        #[prost(message, tag="4")]
        CancelSell(super::CancelSellInstruction),
        #[prost(message, tag="5")]
        Buy(super::BuyInstruction),
        #[prost(message, tag="6")]
        BuyV2(super::BuyV2Instruction),
        #[prost(message, tag="7")]
        CancelBuy(super::CancelBuyInstruction),
        #[prost(message, tag="8")]
        ExecuteSaleV2(super::ExecuteSaleV2Instruction),
        #[prost(message, tag="9")]
        OcpSell(super::OcpSellInstruction),
        #[prost(message, tag="10")]
        OcpExecuteSaleV2(super::OcpExecuteSaleV2Instruction),
        #[prost(message, tag="11")]
        Mip1Sell(super::Mip1SellInstruction),
        #[prost(message, tag="12")]
        Mip1ExecuteSaleV2(super::Mip1ExecuteSaleV2Instruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SellInstruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub seller_state_expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelSellInstruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub seller_state_expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyInstruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub buyer_state_expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyV2Instruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub buyer_state_expiry: i64,
    #[prost(uint32, tag="4")]
    pub buyer_creator_royalty_bp: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelBuyInstruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub buyer_state_expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteSaleV2Instruction {
    #[prost(uint64, tag="1")]
    pub buyer_price: u64,
    #[prost(uint64, tag="2")]
    pub token_size: u64,
    #[prost(int64, tag="3")]
    pub buyer_state_expiry: i64,
    #[prost(int64, tag="4")]
    pub seller_state_expiry: i64,
    #[prost(int32, tag="5")]
    pub maker_fee_bp: i32,
    #[prost(uint32, tag="6")]
    pub taker_fee_bp: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OcpSellInstruction {
    #[prost(uint64, tag="1")]
    pub price: u64,
    #[prost(int64, tag="2")]
    pub expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OcpExecuteSaleV2Instruction {
    #[prost(uint64, tag="1")]
    pub price: u64,
    #[prost(int32, tag="2")]
    pub maker_fee_bp: i32,
    #[prost(uint32, tag="3")]
    pub taker_fee_bp: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mip1SellInstruction {
    #[prost(uint64, tag="1")]
    pub price: u64,
    #[prost(int64, tag="2")]
    pub expiry: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mip1ExecuteSaleV2Instruction {
    #[prost(uint64, tag="1")]
    pub price: u64,
    #[prost(int32, tag="2")]
    pub maker_fee_bp: i32,
    #[prost(uint32, tag="3")]
    pub taker_fee_bp: u32,
}
// @@protoc_insertion_point(module)
