// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6, 7, 8, 9, 10")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        Deposit(super::DepositInstruction),
        #[prost(message, tag="4")]
        DepositStakeAccount(super::DepositStakeAccountInstruction),
        #[prost(message, tag="5")]
        LiquidUnstake(super::LiquidUnstakeInstruction),
        #[prost(message, tag="6")]
        AddLiquidity(super::AddLiquidityInstruction),
        #[prost(message, tag="7")]
        RemoveLiquidity(super::RemoveLiquidityInstruction),
        #[prost(message, tag="8")]
        OrderUnstake(super::OrderUnstakeInstruction),
        #[prost(message, tag="9")]
        Claim(super::ClaimInstruction),
        #[prost(message, tag="10")]
        WithdrawStakeAccount(super::WithdrawStakeAccountInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositInstruction {
    #[prost(uint64, tag="1")]
    pub lamports: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositStakeAccountInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidUnstakeInstruction {
    #[prost(uint64, tag="1")]
    pub msol_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidityInstruction {
    #[prost(uint64, tag="1")]
    pub lamports: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityInstruction {
    #[prost(uint64, tag="1")]
    pub tokens: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderUnstakeInstruction {
    #[prost(uint64, tag="1")]
    pub msol_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawStakeAccountInstruction {
    #[prost(uint64, tag="1")]
    pub msol_amount: u64,
    #[prost(uint32, tag="2")]
    pub stake_index: u32,
    #[prost(uint32, tag="3")]
    pub validator_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4, 5, 6, 7, 8")]
    pub log: ::core::option::Option<log::Log>,
}
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        Deposit(super::DepositEvent),
        #[prost(message, tag="4")]
        DepositStakeAccount(super::DepositStakeAccountEvent),
        #[prost(message, tag="5")]
        LiquidUnstake(super::LiquidUnstakeEvent),
        #[prost(message, tag="6")]
        AddLiquidity(super::AddLiquidityEvent),
        #[prost(message, tag="7")]
        RemoveLiquidity(super::RemoveLiquidityEvent),
        #[prost(message, tag="8")]
        WithdrawStakeAccount(super::WithdrawStakeAccountEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub sol_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub sol_swapped: u64,
    #[prost(uint64, tag="4")]
    pub msol_swapped: u64,
    #[prost(uint64, tag="5")]
    pub sol_deposited: u64,
    #[prost(uint64, tag="6")]
    pub msol_minted: u64,
    #[prost(uint64, tag="7")]
    pub total_virtual_staked_lamports: u64,
    #[prost(uint64, tag="8")]
    pub msol_supply: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositStakeAccountEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub stake: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub delegated: u64,
    #[prost(bytes="vec", tag="4")]
    pub withdrawer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub validator: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub msol_minted: u64,
    #[prost(uint64, tag="7")]
    pub total_virtual_staked_lamports: u64,
    #[prost(uint64, tag="8")]
    pub msol_supply: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidUnstakeEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub msol_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub msol_amount: u64,
    #[prost(uint64, tag="4")]
    pub msol_fee: u64,
    #[prost(uint64, tag="5")]
    pub treasury_msol_cut: u64,
    #[prost(uint64, tag="6")]
    pub sol_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidityEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub sol_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub sol_added_amount: u64,
    #[prost(uint64, tag="4")]
    pub lp_minted: u64,
    #[prost(uint64, tag="5")]
    pub total_virtual_staked_lamports: u64,
    #[prost(uint64, tag="6")]
    pub msol_supply: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub lp_burned: u64,
    #[prost(uint64, tag="3")]
    pub sol_out_amount: u64,
    #[prost(uint64, tag="4")]
    pub msol_out_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawStakeAccountEvent {
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub stake: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub validator: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub user_msol_auth: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub msol_burned: u64,
    #[prost(uint64, tag="6")]
    pub msol_fees: u64,
    #[prost(bytes="vec", tag="7")]
    pub beneficiary: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="8")]
    pub split_lamports: u64,
}
// @@protoc_insertion_point(module)
