// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        PlaceOrder(super::PlaceOrderInstruction),
        #[prost(message, tag="4")]
        PlaceOrders(super::PlaceOrdersInstruction),
        #[prost(message, tag="5")]
        PlaceTakeOrder(super::PlaceTakeOrderInstruction),
        #[prost(message, tag="6")]
        CancelAllAndPlaceOrders(super::CancelAllAndPlaceOrdersInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceOrderInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceOrdersInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceTakeOrderInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelAllAndPlaceOrdersInstruction {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        FillLog(super::FillLogEvent),
        #[prost(message, tag="4")]
        TotalOrderFill(super::TotalOrderFillEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FillLogEvent {
    #[prost(bytes="vec", tag="1")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub taker_side: u32,
    #[prost(uint32, tag="3")]
    pub maker_slot: u32,
    #[prost(bool, tag="4")]
    pub maker_out: bool,
    #[prost(uint64, tag="5")]
    pub timestamp: u64,
    #[prost(uint64, tag="6")]
    pub seq_num: u64,
    #[prost(bytes="vec", tag="7")]
    pub maker: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="8")]
    pub maker_client_order_id: u64,
    #[prost(uint64, tag="9")]
    pub maker_fee: u64,
    #[prost(uint64, tag="10")]
    pub maker_timestamp: u64,
    #[prost(bytes="vec", tag="11")]
    pub taker: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub taker_client_order_id: u64,
    #[prost(uint64, tag="13")]
    pub taker_fee_ceil: u64,
    #[prost(int64, tag="14")]
    pub price: i64,
    #[prost(int64, tag="15")]
    pub quantity: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TotalOrderFillEvent {
    #[prost(uint32, tag="1")]
    pub side: u32,
    #[prost(bytes="vec", tag="2")]
    pub taker: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub total_quantity_paid: u64,
    #[prost(uint64, tag="4")]
    pub total_quantity_received: u64,
    #[prost(uint64, tag="5")]
    pub fees: u64,
}
// @@protoc_insertion_point(module)
