// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        Swap(super::SwapInstruction),
        #[prost(message, tag="4")]
        SwapV2(super::SwapV2Instruction),
        #[prost(message, tag="5")]
        TwoHopSwap(super::TwoHopSwapInstruction),
        #[prost(message, tag="6")]
        TwoHopSwapV2(super::TwoHopSwapV2Instruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapAccounts {
    #[prost(bytes="vec", tag="1")]
    pub token_program: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub token_owner_account_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub token_vault_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub token_owner_account_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_vault_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub tick_array0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub tick_array1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub tick_array2: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapV2Accounts {
    #[prost(bytes="vec", tag="1")]
    pub token_program_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token_program_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub memo_program: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub token_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub token_mint_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_mint_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub token_owner_account_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub token_vault_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub token_owner_account_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub token_vault_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub tick_array0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub tick_array1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub tick_array2: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapInstruction {
    #[prost(message, optional, tag="1")]
    pub accounts: ::core::option::Option<SwapAccounts>,
    #[prost(uint64, tag="2")]
    pub amount: u64,
    #[prost(uint64, tag="3")]
    pub other_amount_threshold: u64,
    #[prost(string, tag="4")]
    pub sqrt_price_limit: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub amount_specified_is_input: bool,
    #[prost(bool, tag="6")]
    pub a_to_b: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapV2Instruction {
    #[prost(message, optional, tag="1")]
    pub accounts: ::core::option::Option<SwapV2Accounts>,
    #[prost(uint64, tag="2")]
    pub amount: u64,
    #[prost(uint64, tag="3")]
    pub other_amount_threshold: u64,
    #[prost(string, tag="4")]
    pub sqrt_price_limit: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub amount_specified_is_input: bool,
    #[prost(bool, tag="6")]
    pub a_to_b: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwoHopSwapInstruction {
    #[prost(uint64, tag="1")]
    pub amount: u64,
    #[prost(uint64, tag="2")]
    pub other_amount_threshold: u64,
    #[prost(bool, tag="3")]
    pub amount_specified_is_input: bool,
    #[prost(bool, tag="4")]
    pub a_to_b_one: bool,
    #[prost(bool, tag="5")]
    pub a_to_b_two: bool,
    #[prost(string, tag="6")]
    pub sqrt_price_limit_one: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub sqrt_price_limit_two: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwoHopSwapV2Instruction {
    #[prost(uint64, tag="1")]
    pub amount: u64,
    #[prost(uint64, tag="2")]
    pub other_amount_threshold: u64,
    #[prost(bool, tag="3")]
    pub amount_specified_is_input: bool,
    #[prost(bool, tag="4")]
    pub a_to_b_one: bool,
    #[prost(bool, tag="5")]
    pub a_to_b_two: bool,
    #[prost(string, tag="6")]
    pub sqrt_price_limit_one: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub sqrt_price_limit_two: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4, 5, 6")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        Traded(super::TradedEvent),
        #[prost(message, tag="4")]
        PoolInitialized(super::PoolInitializedEvent),
        #[prost(message, tag="5")]
        LiquidityIncreased(super::LiquidityIncreasedEvent),
        #[prost(message, tag="6")]
        LiquidityDecreased(super::LiquidityDecreasedEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradedEvent {
    #[prost(bytes="vec", tag="1")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="2")]
    pub a_to_b: bool,
    #[prost(string, tag="3")]
    pub pre_sqrt_price: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub post_sqrt_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub input_amount: u64,
    #[prost(uint64, tag="6")]
    pub output_amount: u64,
    #[prost(uint64, tag="7")]
    pub input_transfer_fee: u64,
    #[prost(uint64, tag="8")]
    pub output_transfer_fee: u64,
    #[prost(uint64, tag="9")]
    pub lp_fee: u64,
    #[prost(uint64, tag="10")]
    pub protocol_fee: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolInitializedEvent {
    #[prost(bytes="vec", tag="1")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub whirlpools_config: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub token_mint_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub token_mint_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub tick_spacing: u32,
    #[prost(bytes="vec", tag="6")]
    pub token_program_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_program_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="8")]
    pub decimals_a: u32,
    #[prost(uint32, tag="9")]
    pub decimals_b: u32,
    #[prost(string, tag="10")]
    pub initial_sqrt_price: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityIncreasedEvent {
    #[prost(bytes="vec", tag="1")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub position: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag="3")]
    pub tick_lower_index: i32,
    #[prost(int32, tag="4")]
    pub tick_upper_index: i32,
    #[prost(string, tag="5")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub token_a_amount: u64,
    #[prost(uint64, tag="7")]
    pub token_b_amount: u64,
    #[prost(uint64, tag="8")]
    pub token_a_transfer_fee: u64,
    #[prost(uint64, tag="9")]
    pub token_b_transfer_fee: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityDecreasedEvent {
    #[prost(bytes="vec", tag="1")]
    pub whirlpool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub position: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag="3")]
    pub tick_lower_index: i32,
    #[prost(int32, tag="4")]
    pub tick_upper_index: i32,
    #[prost(string, tag="5")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub token_a_amount: u64,
    #[prost(uint64, tag="7")]
    pub token_b_amount: u64,
    #[prost(uint64, tag="8")]
    pub token_a_transfer_fee: u64,
    #[prost(uint64, tag="9")]
    pub token_b_transfer_fee: u64,
}
// @@protoc_insertion_point(module)
