// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        Buy(super::BuyInstruction),
        #[prost(message, tag="4")]
        BuyExactQuoteIn(super::BuyExactQuoteInInstruction),
        #[prost(message, tag="5")]
        Sell(super::SellInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyInstruction {
    #[prost(uint64, tag="1")]
    pub base_amount_out: u64,
    #[prost(uint64, tag="2")]
    pub max_quote_amount_in: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyExactQuoteInInstruction {
    #[prost(uint64, tag="1")]
    pub spendable_quote_in: u64,
    #[prost(uint64, tag="2")]
    pub min_base_amount_out: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SellInstruction {
    #[prost(uint64, tag="1")]
    pub base_amount_in: u64,
    #[prost(uint64, tag="2")]
    pub min_quote_amount_out: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4, 5")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        Buy(super::BuyEvent),
        #[prost(message, tag="4")]
        Sell(super::SellEvent),
        #[prost(message, tag="5")]
        CreatePool(super::CreatePoolEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(uint64, tag="2")]
    pub base_amount_out: u64,
    #[prost(uint64, tag="3")]
    pub max_quote_amount_in: u64,
    #[prost(uint64, tag="4")]
    pub user_base_token_reserves: u64,
    #[prost(uint64, tag="5")]
    pub user_quote_token_reserves: u64,
    #[prost(uint64, tag="6")]
    pub pool_base_token_reserves: u64,
    #[prost(uint64, tag="7")]
    pub pool_quote_token_reserves: u64,
    #[prost(uint64, tag="8")]
    pub quote_amount_in: u64,
    #[prost(uint64, tag="9")]
    pub lp_fee_basis_points: u64,
    #[prost(uint64, tag="10")]
    pub lp_fee: u64,
    #[prost(uint64, tag="11")]
    pub protocol_fee_basis_points: u64,
    #[prost(uint64, tag="12")]
    pub protocol_fee: u64,
    #[prost(uint64, tag="13")]
    pub quote_amount_in_with_lp_fee: u64,
    #[prost(uint64, tag="14")]
    pub user_quote_amount_in: u64,
    #[prost(bytes="vec", tag="15")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub coin_creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="18")]
    pub coin_creator_fee_basis_points: u64,
    #[prost(uint64, tag="19")]
    pub coin_creator_fee: u64,
    #[prost(uint64, tag="20")]
    pub min_base_amount_out: u64,
    #[prost(string, tag="21")]
    pub ix_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SellEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(uint64, tag="2")]
    pub base_amount_in: u64,
    #[prost(uint64, tag="3")]
    pub min_quote_amount_out: u64,
    #[prost(uint64, tag="4")]
    pub user_base_token_reserves: u64,
    #[prost(uint64, tag="5")]
    pub user_quote_token_reserves: u64,
    #[prost(uint64, tag="6")]
    pub pool_base_token_reserves: u64,
    #[prost(uint64, tag="7")]
    pub pool_quote_token_reserves: u64,
    #[prost(uint64, tag="8")]
    pub quote_amount_out: u64,
    #[prost(uint64, tag="9")]
    pub lp_fee_basis_points: u64,
    #[prost(uint64, tag="10")]
    pub lp_fee: u64,
    #[prost(uint64, tag="11")]
    pub protocol_fee_basis_points: u64,
    #[prost(uint64, tag="12")]
    pub protocol_fee: u64,
    #[prost(uint64, tag="13")]
    pub quote_amount_out_without_lp_fee: u64,
    #[prost(uint64, tag="14")]
    pub user_quote_amount_out: u64,
    #[prost(bytes="vec", tag="15")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub coin_creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="18")]
    pub coin_creator_fee_basis_points: u64,
    #[prost(uint64, tag="19")]
    pub coin_creator_fee: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePoolEvent {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(uint32, tag="2")]
    pub index: u32,
    #[prost(bytes="vec", tag="3")]
    pub creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub base_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub quote_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="6")]
    pub base_mint_decimals: u32,
    #[prost(uint32, tag="7")]
    pub quote_mint_decimals: u32,
    #[prost(uint64, tag="8")]
    pub base_amount_in: u64,
    #[prost(uint64, tag="9")]
    pub quote_amount_in: u64,
    #[prost(uint64, tag="10")]
    pub pool_base_amount: u64,
    #[prost(uint64, tag="11")]
    pub pool_quote_amount: u64,
    #[prost(uint64, tag="12")]
    pub minimum_liquidity: u64,
    #[prost(uint64, tag="13")]
    pub initial_liquidity: u64,
    #[prost(uint64, tag="14")]
    pub lp_token_amount_out: u64,
    #[prost(uint32, tag="15")]
    pub pool_bump: u32,
    #[prost(bytes="vec", tag="16")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub lp_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="18")]
    pub coin_creator: ::prost::alloc::vec::Vec<u8>,
}
