// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Fee payer account address.
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    /// Signers of the transaction.
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Lamports paid for this instruction.
    #[prost(uint64, tag="4")]
    pub fee: u64,
    /// Compute units consumed by this instruction.
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    /// Instructions executed in this transaction.
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    /// Indicates if this instruction is a root instruction.
    #[prost(bool, tag="3")]
    pub is_root: bool,
    #[prost(oneof="instruction::Instruction", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="10")]
        InitLendingMarket(super::InitLendingMarket),
        #[prost(message, tag="11")]
        InitReserve(super::InitReserve),
        #[prost(message, tag="12")]
        DepositReserveLiquidity(super::DepositReserveLiquidity),
        #[prost(message, tag="13")]
        RedeemReserveCollateral(super::RedeemReserveCollateral),
        #[prost(message, tag="14")]
        InitObligation(super::InitObligation),
        #[prost(message, tag="15")]
        DepositObligationCollateral(super::DepositObligationCollateral),
        #[prost(message, tag="16")]
        WithdrawObligationCollateral(super::WithdrawObligationCollateral),
        #[prost(message, tag="17")]
        BorrowObligationLiquidity(super::BorrowObligationLiquidity),
        #[prost(message, tag="18")]
        RepayObligationLiquidity(super::RepayObligationLiquidity),
        #[prost(message, tag="19")]
        LiquidateObligation(super::LiquidateObligation),
        #[prost(message, tag="20")]
        FlashLoan(super::FlashLoan),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitLendingMarket {
    /// Lending market account.
    #[prost(bytes="vec", tag="1")]
    pub lending_market: ::prost::alloc::vec::Vec<u8>,
    /// Market owner.
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// Quote currency.
    #[prost(bytes="vec", tag="3")]
    pub quote_currency: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitReserve {
    /// Lending market account.
    #[prost(bytes="vec", tag="1")]
    pub lending_market: ::prost::alloc::vec::Vec<u8>,
    /// Reserve account.
    #[prost(bytes="vec", tag="2")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Liquidity token mint.
    #[prost(bytes="vec", tag="3")]
    pub liquidity_mint: ::prost::alloc::vec::Vec<u8>,
    /// Liquidity supply account.
    #[prost(bytes="vec", tag="4")]
    pub liquidity_supply: ::prost::alloc::vec::Vec<u8>,
    /// Collateral token mint.
    #[prost(bytes="vec", tag="5")]
    pub collateral_mint: ::prost::alloc::vec::Vec<u8>,
    /// Collateral supply account.
    #[prost(bytes="vec", tag="6")]
    pub collateral_supply: ::prost::alloc::vec::Vec<u8>,
    /// Initial liquidity amount.
    #[prost(uint64, tag="7")]
    pub liquidity_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositReserveLiquidity {
    /// Reserve account.
    #[prost(bytes="vec", tag="1")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Source liquidity token account.
    #[prost(bytes="vec", tag="2")]
    pub source_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Destination collateral token account.
    #[prost(bytes="vec", tag="3")]
    pub destination_collateral: ::prost::alloc::vec::Vec<u8>,
    /// Amount of liquidity to deposit.
    #[prost(uint64, tag="4")]
    pub liquidity_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedeemReserveCollateral {
    /// Reserve account.
    #[prost(bytes="vec", tag="1")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Source collateral token account.
    #[prost(bytes="vec", tag="2")]
    pub source_collateral: ::prost::alloc::vec::Vec<u8>,
    /// Destination liquidity token account.
    #[prost(bytes="vec", tag="3")]
    pub destination_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Amount of collateral to redeem.
    #[prost(uint64, tag="4")]
    pub collateral_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitObligation {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Lending market account.
    #[prost(bytes="vec", tag="2")]
    pub lending_market: ::prost::alloc::vec::Vec<u8>,
    /// Obligation owner.
    #[prost(bytes="vec", tag="3")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositObligationCollateral {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Source collateral token account.
    #[prost(bytes="vec", tag="2")]
    pub source_collateral: ::prost::alloc::vec::Vec<u8>,
    /// Reserve account.
    #[prost(bytes="vec", tag="3")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Amount of collateral to deposit.
    #[prost(uint64, tag="4")]
    pub collateral_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawObligationCollateral {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Destination collateral token account.
    #[prost(bytes="vec", tag="2")]
    pub destination_collateral: ::prost::alloc::vec::Vec<u8>,
    /// Reserve account.
    #[prost(bytes="vec", tag="3")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Amount of collateral to withdraw.
    #[prost(uint64, tag="4")]
    pub collateral_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BorrowObligationLiquidity {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Destination liquidity token account.
    #[prost(bytes="vec", tag="2")]
    pub destination_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Reserve account.
    #[prost(bytes="vec", tag="3")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Amount of liquidity to borrow.
    #[prost(uint64, tag="4")]
    pub liquidity_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepayObligationLiquidity {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Source liquidity token account.
    #[prost(bytes="vec", tag="2")]
    pub source_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Reserve account.
    #[prost(bytes="vec", tag="3")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Amount of liquidity to repay.
    #[prost(uint64, tag="4")]
    pub liquidity_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidateObligation {
    /// Obligation account.
    #[prost(bytes="vec", tag="1")]
    pub obligation: ::prost::alloc::vec::Vec<u8>,
    /// Repay reserve account.
    #[prost(bytes="vec", tag="2")]
    pub repay_reserve: ::prost::alloc::vec::Vec<u8>,
    /// Withdraw reserve account.
    #[prost(bytes="vec", tag="3")]
    pub withdraw_reserve: ::prost::alloc::vec::Vec<u8>,
    /// Source liquidity token account.
    #[prost(bytes="vec", tag="4")]
    pub source_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Destination collateral token account.
    #[prost(bytes="vec", tag="5")]
    pub destination_collateral: ::prost::alloc::vec::Vec<u8>,
    /// Amount of liquidity to repay.
    #[prost(uint64, tag="6")]
    pub liquidity_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlashLoan {
    /// Reserve account.
    #[prost(bytes="vec", tag="1")]
    pub reserve: ::prost::alloc::vec::Vec<u8>,
    /// Source liquidity token account.
    #[prost(bytes="vec", tag="2")]
    pub source_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Destination liquidity token account.
    #[prost(bytes="vec", tag="3")]
    pub destination_liquidity: ::prost::alloc::vec::Vec<u8>,
    /// Amount of flash loan.
    #[prost(uint64, tag="4")]
    pub amount: u64,
}
// @@protoc_insertion_point(module)
