// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// <https://github.com/solana-program/token-2022>
    #[prost(message, repeated, tag="1")]
    pub balances: ::prost::alloc::vec::Vec<Balance>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    /// -- transaction --
    #[prost(bytes="vec", tag="1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// -- indexes --
    #[prost(uint32, tag="2")]
    pub execution_index: u32,
    /// -- account --
    #[prost(bytes="vec", tag="10")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    /// -- event --
    #[prost(bytes="vec", tag="11")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub amount: u64,
    /// uint8
    #[prost(uint32, tag="14")]
    pub decimals: u32,
}
// @@protoc_insertion_point(module)
