// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Fee payer account address.
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    /// Signers of the transaction.
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Lamports paid for this instruction.
    #[prost(uint64, tag="4")]
    pub fee: u64,
    /// Compute units consumed by this instruction.
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    /// Instructions executed in this transaction.
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    /// Indicates if this instruction is a root instruction.
    #[prost(bool, tag="3")]
    pub is_root: bool,
    #[prost(oneof="instruction::Instruction", tags="10, 11, 12, 13, 14, 15")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="10")]
        Initialize(super::Initialize),
        #[prost(message, tag="11")]
        Delegate(super::Delegate),
        #[prost(message, tag="12")]
        Deactivate(super::Deactivate),
        #[prost(message, tag="13")]
        Withdraw(super::Withdraw),
        #[prost(message, tag="14")]
        Merge(super::Merge),
        #[prost(message, tag="15")]
        Split(super::Split),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    /// Stake account to initialize.
    #[prost(bytes="vec", tag="1")]
    pub stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Staker authority.
    #[prost(bytes="vec", tag="2")]
    pub staker: ::prost::alloc::vec::Vec<u8>,
    /// Withdrawer authority.
    #[prost(bytes="vec", tag="3")]
    pub withdrawer: ::prost::alloc::vec::Vec<u8>,
    /// Lockup timestamp.
    #[prost(int64, optional, tag="4")]
    pub lockup_unix_timestamp: ::core::option::Option<i64>,
    /// Lockup epoch.
    #[prost(uint64, optional, tag="5")]
    pub lockup_epoch: ::core::option::Option<u64>,
    /// Lockup custodian.
    #[prost(bytes="vec", optional, tag="6")]
    pub lockup_custodian: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Delegate {
    /// Stake account.
    #[prost(bytes="vec", tag="1")]
    pub stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Vote account to delegate to.
    #[prost(bytes="vec", tag="2")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Stake authority.
    #[prost(bytes="vec", tag="3")]
    pub stake_authority: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deactivate {
    /// Stake account to deactivate.
    #[prost(bytes="vec", tag="1")]
    pub stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Stake authority.
    #[prost(bytes="vec", tag="2")]
    pub stake_authority: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    /// Stake account.
    #[prost(bytes="vec", tag="1")]
    pub stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Destination account.
    #[prost(bytes="vec", tag="2")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    /// Amount to withdraw.
    #[prost(uint64, tag="3")]
    pub lamports: u64,
    /// Withdraw authority.
    #[prost(bytes="vec", tag="4")]
    pub withdraw_authority: ::prost::alloc::vec::Vec<u8>,
    /// Lockup custodian (optional).
    #[prost(bytes="vec", optional, tag="5")]
    pub custodian: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Merge {
    /// Destination stake account.
    #[prost(bytes="vec", tag="1")]
    pub destination_stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Source stake account (to merge from).
    #[prost(bytes="vec", tag="2")]
    pub source_stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Stake authority.
    #[prost(bytes="vec", tag="3")]
    pub stake_authority: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Split {
    /// Source stake account.
    #[prost(bytes="vec", tag="1")]
    pub stake_account: ::prost::alloc::vec::Vec<u8>,
    /// New split stake account.
    #[prost(bytes="vec", tag="2")]
    pub split_stake_account: ::prost::alloc::vec::Vec<u8>,
    /// Amount to split.
    #[prost(uint64, tag="3")]
    pub lamports: u64,
    /// Stake authority.
    #[prost(bytes="vec", tag="4")]
    pub stake_authority: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
