// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Fee payer account address.
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    /// Signers of the transaction.
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Lamports paid for this instruction.
    #[prost(uint64, tag="4")]
    pub fee: u64,
    /// Compute units consumed by this instruction.
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    /// Instructions executed in this transaction.
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    /// Indicates if this instruction is a root instruction.
    #[prost(bool, tag="3")]
    pub is_root: bool,
    #[prost(oneof="instruction::Instruction", tags="10, 11, 12, 13, 14, 15")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="10")]
        Initialize(super::Initialize),
        #[prost(message, tag="11")]
        Swap(super::Swap),
        #[prost(message, tag="12")]
        DepositAllTokenTypes(super::DepositAllTokenTypes),
        #[prost(message, tag="13")]
        WithdrawAllTokenTypes(super::WithdrawAllTokenTypes),
        #[prost(message, tag="14")]
        DepositSingleTokenTypeExactAmountIn(super::DepositSingleTokenTypeExactAmountIn),
        #[prost(message, tag="15")]
        WithdrawSingleTokenTypeExactAmountOut(super::WithdrawSingleTokenTypeExactAmountOut),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    /// Token swap account.
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    /// Swap authority.
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    /// Token A account.
    #[prost(bytes="vec", tag="3")]
    pub token_a: ::prost::alloc::vec::Vec<u8>,
    /// Token B account.
    #[prost(bytes="vec", tag="4")]
    pub token_b: ::prost::alloc::vec::Vec<u8>,
    /// Pool token mint.
    #[prost(bytes="vec", tag="5")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    /// Fee account.
    #[prost(bytes="vec", tag="6")]
    pub fee_account: ::prost::alloc::vec::Vec<u8>,
    /// Destination for initial pool tokens.
    #[prost(bytes="vec", tag="7")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    /// Token swap account.
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    /// Swap authority.
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    /// User transfer authority.
    #[prost(bytes="vec", tag="3")]
    pub user_transfer_authority: ::prost::alloc::vec::Vec<u8>,
    /// Source token account.
    #[prost(bytes="vec", tag="4")]
    pub source: ::prost::alloc::vec::Vec<u8>,
    /// Swap source token account.
    #[prost(bytes="vec", tag="5")]
    pub swap_source: ::prost::alloc::vec::Vec<u8>,
    /// Swap destination token account.
    #[prost(bytes="vec", tag="6")]
    pub swap_destination: ::prost::alloc::vec::Vec<u8>,
    /// Destination token account.
    #[prost(bytes="vec", tag="7")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    /// Pool token mint.
    #[prost(bytes="vec", tag="8")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    /// Fee account.
    #[prost(bytes="vec", tag="9")]
    pub fee_account: ::prost::alloc::vec::Vec<u8>,
    /// Amount of tokens to swap.
    #[prost(uint64, tag="10")]
    pub amount_in: u64,
    /// Minimum amount of tokens to receive.
    #[prost(uint64, tag="11")]
    pub minimum_amount_out: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositAllTokenTypes {
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub user_transfer_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub source_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub source_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub token_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub pool_token_amount: u64,
    #[prost(uint64, tag="11")]
    pub maximum_token_a_amount: u64,
    #[prost(uint64, tag="12")]
    pub maximum_token_b_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawAllTokenTypes {
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub user_transfer_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub fee_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub source: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub token_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub destination_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub destination_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="11")]
    pub pool_token_amount: u64,
    #[prost(uint64, tag="12")]
    pub minimum_token_a_amount: u64,
    #[prost(uint64, tag="13")]
    pub minimum_token_b_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositSingleTokenTypeExactAmountIn {
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub user_transfer_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub source: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub token_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub token_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="9")]
    pub source_token_amount: u64,
    #[prost(uint64, tag="10")]
    pub minimum_pool_token_amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawSingleTokenTypeExactAmountOut {
    #[prost(bytes="vec", tag="1")]
    pub swap_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub user_transfer_authority: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub pool_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub fee_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub source: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token_a: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub token_b: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub destination_token_amount: u64,
    #[prost(uint64, tag="11")]
    pub maximum_pool_token_amount: u64,
}
// @@protoc_insertion_point(module)
