// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolanaClock {
    #[prost(bytes="vec", tag="1")]
    pub blockhash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub slot: u64,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
}
// @@protoc_insertion_point(module)
