// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Fee payer account address.
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    /// Signers of the transaction.
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Lamports paid for this instruction.
    #[prost(uint64, tag="4")]
    pub fee: u64,
    /// Compute units consumed by this instruction.
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    /// Instructions executed in this transaction.
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    /// Indicates if this instruction is a root instruction.
    #[prost(bool, tag="3")]
    pub is_root: bool,
    #[prost(oneof="instruction::Instruction", tags="10, 11, 12, 13, 14, 15, 16")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="10")]
        InitializeAccount(super::InitializeAccount),
        #[prost(message, tag="11")]
        Vote(super::Vote),
        #[prost(message, tag="12")]
        Withdraw(super::Withdraw),
        #[prost(message, tag="13")]
        UpdateValidatorIdentity(super::UpdateValidatorIdentity),
        #[prost(message, tag="14")]
        UpdateCommission(super::UpdateCommission),
        #[prost(message, tag="15")]
        VoteSwitch(super::VoteSwitch),
        #[prost(message, tag="16")]
        CompactUpdateVoteState(super::CompactUpdateVoteState),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeAccount {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Validator identity.
    #[prost(bytes="vec", tag="2")]
    pub node_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// Authorized voter.
    #[prost(bytes="vec", tag="3")]
    pub authorized_voter: ::prost::alloc::vec::Vec<u8>,
    /// Authorized withdrawer.
    #[prost(bytes="vec", tag="4")]
    pub authorized_withdrawer: ::prost::alloc::vec::Vec<u8>,
    /// Commission percentage (0-100).
    #[prost(uint32, tag="5")]
    pub commission: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vote {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Vote authority.
    #[prost(bytes="vec", tag="2")]
    pub vote_authority: ::prost::alloc::vec::Vec<u8>,
    /// Slots voted on.
    #[prost(uint64, repeated, tag="3")]
    pub slots: ::prost::alloc::vec::Vec<u64>,
    /// Recent block hash.
    #[prost(bytes="vec", tag="4")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Destination account.
    #[prost(bytes="vec", tag="2")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    /// Amount to withdraw.
    #[prost(uint64, tag="3")]
    pub lamports: u64,
    /// Withdraw authority.
    #[prost(bytes="vec", tag="4")]
    pub withdraw_authority: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateValidatorIdentity {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// New validator identity.
    #[prost(bytes="vec", tag="2")]
    pub node_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// Authorized withdrawer.
    #[prost(bytes="vec", tag="3")]
    pub authorized_withdrawer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateCommission {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// New commission percentage (0-100).
    #[prost(uint32, tag="2")]
    pub commission: u32,
    /// Authorized withdrawer.
    #[prost(bytes="vec", tag="3")]
    pub authorized_withdrawer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoteSwitch {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Vote authority.
    #[prost(bytes="vec", tag="2")]
    pub vote_authority: ::prost::alloc::vec::Vec<u8>,
    /// Slots voted on.
    #[prost(uint64, repeated, tag="3")]
    pub slots: ::prost::alloc::vec::Vec<u64>,
    /// Recent block hash.
    #[prost(bytes="vec", tag="4")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// Proof hash for the switch.
    #[prost(bytes="vec", tag="5")]
    pub proof_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactUpdateVoteState {
    /// Vote account.
    #[prost(bytes="vec", tag="1")]
    pub vote_account: ::prost::alloc::vec::Vec<u8>,
    /// Vote authority.
    #[prost(bytes="vec", tag="2")]
    pub vote_authority: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
