// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="7")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub stack_height: u32,
    #[prost(oneof="instruction::Instruction", tags="3, 4, 5, 6, 7, 8")]
    pub instruction: ::core::option::Option<instruction::Instruction>,
}
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Instruction {
        #[prost(message, tag="3")]
        List(super::ListInstruction),
        #[prost(message, tag="4")]
        Delist(super::DelistInstruction),
        #[prost(message, tag="5")]
        Edit(super::EditInstruction),
        #[prost(message, tag="6")]
        Buy(super::BuyInstruction),
        #[prost(message, tag="7")]
        Bid(super::BidInstruction),
        #[prost(message, tag="8")]
        TakeBid(super::TakeBidInstruction),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInstruction {
    #[prost(uint64, tag="1")]
    pub amount: u64,
    #[prost(uint64, optional, tag="2")]
    pub expire_in_sec: ::core::option::Option<u64>,
    #[prost(bytes="vec", optional, tag="3")]
    pub currency: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="4")]
    pub private_taker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="5")]
    pub maker_broker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag="6")]
    pub nft_standard: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelistInstruction {
    #[prost(string, tag="1")]
    pub nft_standard: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditInstruction {
    #[prost(uint64, tag="1")]
    pub amount: u64,
    #[prost(uint64, optional, tag="2")]
    pub expire_in_sec: ::core::option::Option<u64>,
    #[prost(bytes="vec", optional, tag="3")]
    pub currency: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="4")]
    pub private_taker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="5")]
    pub maker_broker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyInstruction {
    #[prost(uint64, tag="1")]
    pub max_amount: u64,
    #[prost(string, tag="2")]
    pub nft_standard: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BidInstruction {
    #[prost(bytes="vec", tag="1")]
    pub bid_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub target: u32,
    #[prost(bytes="vec", tag="3")]
    pub target_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub amount: u64,
    #[prost(uint32, tag="5")]
    pub quantity: u32,
    #[prost(uint64, optional, tag="6")]
    pub expire_in_sec: ::core::option::Option<u64>,
    #[prost(bytes="vec", optional, tag="7")]
    pub currency: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="8")]
    pub private_taker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="9")]
    pub maker_broker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TakeBidInstruction {
    #[prost(uint64, tag="1")]
    pub min_amount: u64,
    #[prost(string, tag="2")]
    pub nft_standard: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub invoke_depth: u32,
    #[prost(oneof="log::Log", tags="3, 4")]
    pub log: ::core::option::Option<log::Log>,
}
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="3")]
        Make(super::MakeEvent),
        #[prost(message, tag="4")]
        Take(super::TakeEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MakeEvent {
    #[prost(bytes="vec", tag="1")]
    pub maker: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="2")]
    pub bid_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag="3")]
    pub target: u32,
    #[prost(bytes="vec", tag="4")]
    pub target_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub amount: u64,
    #[prost(uint32, tag="6")]
    pub quantity: u32,
    #[prost(bytes="vec", optional, tag="7")]
    pub currency: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(int64, tag="8")]
    pub expiry: i64,
    #[prost(bytes="vec", optional, tag="9")]
    pub private_taker: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="10")]
    pub asset_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TakeEvent {
    #[prost(bytes="vec", tag="1")]
    pub taker: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="2")]
    pub bid_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag="3")]
    pub target: u32,
    #[prost(bytes="vec", tag="4")]
    pub target_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub amount: u64,
    #[prost(uint32, tag="6")]
    pub quantity: u32,
    #[prost(uint64, tag="7")]
    pub tcomp_fee: u64,
    #[prost(uint64, tag="8")]
    pub taker_broker_fee: u64,
    #[prost(uint64, tag="9")]
    pub maker_broker_fee: u64,
    #[prost(uint64, tag="10")]
    pub creator_fee: u64,
    #[prost(bytes="vec", optional, tag="11")]
    pub currency: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="12")]
    pub asset_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
// @@protoc_insertion_point(module)
