CREATE TABLE IF NOT EXISTS verified_tokens  (
    program_id           FixedString(44),
    description          String
)
ENGINE = ReplacingMergeTree
ORDER BY (program_id);

-- Main Program IDs for supported DEX AMMs
INSERT INTO verified_tokens (program_id, description) VALUES
    ('675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8', 'Raydium Liquidity Pool V4'),
    ('6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P', 'Pump.fun'),
    ('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA', 'Pump.fun AMM'),
    ('JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB', 'Jupiter Aggregator v4'),
    ('JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4', 'Jupiter Aggregator v6');

-- Program IDs derived from the Jupiter V4/V6 aggregator
INSERT INTO verified_tokens (program_id, description) VALUES
    ('dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN', 'Meteora Dynamic Bonding Curve Program'),
    ('whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc', 'Whirlpools Program'),
    ('LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo', 'Meteora DLMM Program'),
    ('SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe', 'SolFi'),
    ('CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK', 'Raydium Concentrated Liquidity'),
    ('2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c', 'Lifinity Swap V2'),
    ('cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG', 'Meteora DAMM v2'),
    ('obriQD1zbpyLz95G5n7nJe6a4DPjpFwa5XYPoNm113y', 'Obric V2'),
    ('ZERor4xhbUycZ6gb9ntrhqscUcZmAbQDjEAtCf4hbZY', 'ZeroFi'),
    ('swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ', 'stabble Stable Swap'),
    ('opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb', 'Openbook V2'),
    ('CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C', 'Raydium CPMM'),
    ('goonERTdGsjnkZqWuVjs73BZ3Pb9qoCUdBUL17BnS5j', 'GoonFi'),
    ('Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB', 'Meteora Pools Program'),
    ('DEXYosS6oEGvk8uCDayvwEZz4qEyDJRf9nFgYCaqPMTm', '1Dex Program'),
    ('H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt', 'Cropper Whirlpool'),
    ('GAMMA7meSFWaBXF25oSUgmGRwaW6sCMFLmBNiMSdbHVT', 'GooseFX: GAMMA'),
    ('NUMERUNsFCP3kuNmWZuXtm1AaQCPj9uw6Guv2Ekoi5P', 'Numeraire'),
    ('SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ', 'Saber Stable Swap'),
    ('swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW', 'stabble Weighted Swap'),
    ('HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt', 'Invariant Swap'),
    ('PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY', 'Phoenix'),
    ('LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj', 'Raydium Launchpad'),
    ('SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr', 'Saros AMM'),
    ('PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu', 'Jupiter Perpetuals'),
    ('5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx', 'Sanctum Program'),
    ('9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP', 'Orca Token Swap V2'),
    ('Gswppe6ERWKpUTXvRPfXdzHhiCyJvLadVvXGfdpBqcE1', 'Guac Swap'),
    ('BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p', 'BonkSwap'),
    ('MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG', 'Moonit'),
    ('DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB', 'Saber Decimal Wrapper'),
    ('SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8', 'Swap Program'),
    ('stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq', 'Sanctum Router Program'),
    ('FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X', 'Fluxbeam Program'),
    ('MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky', 'Mercurial Stable Swap'),
    ('srAMMzfVHVAtgSJc8iH6CfKzuWuUTzLHVCE81QU1rgi', 'Gavel'),
    ('SSwpMgqNDsyV7mAgN9ady4bDVu5ySjmmXejXvy2vLt1', 'Step Finance Swap Program'),
    ('DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1', 'Orca Token Swap'),
    ('Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j', 'StepN DOOAR Swap'),
    ('CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4', 'Aldrin AMM V2'),
    ('CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh', 'Cropper Finance'),
    ('SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ', 'Sencha Cpamm'),
    ('treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5', 'Helium Treasury Management'),
    ('9tKE7Mbmj4mxDjWatikzGAtkoWosiiZX9y6J4Hfm2R8H', 'Oasis'),
    ('DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N', 'Dexlab Swap'),
    ('PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP', 'Penguin Finance'),
    ('AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6', 'Aldrin AMM'),
    ('WooFif76YGRNjk1pA8wCsN67aQsD9f9iLsz4NcJ1AVb', 'WOOFi'),
    ('CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR', 'Crema Finance Program'),
    ('EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S', 'Lifinity Swap'),
    ('srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX', 'OpenBook'),
    ('GFXsSL5sSaDfNFQUYsHekbWBW1TsFdjDYzACh62tEHxn', 'GooseFX V2'),
    ('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD', 'Marinade Finance'),
    ('2KehYt3KsEQR53jYcxjbQp2d2kCp4AkuQW68atufRwSr', 'Symmetry Engine'),
    ('D3BBjqUdCYuP18fNvvMbPAZ8DpcRi4io2EsYHQawJDag', 'Sentre Swap'),
    ('cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8', 'Cykura Swap'),
    ('dp2waEWSBy5yKmq65ergoU3G6qRLmqa6K7We4rZSKph', 'Dradex Program'),
    ('7WduLbRfYhTJktjLw5FDEyrqoEv61aTTCuGAetgLjzN5', 'GooseFX SSL'),
    ('C1onEW2kPetmHmwe74YC1ESx3LnFEpVau6g2pg4fHycr', 'Clone'),
    ('1MooN32fuBBgApc8ujknKJw5sef3BVwPGgz3pto1BAh', '1Sol'),
    ('9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin', 'Serum DEX V3');
